import type { Metadata } from "next";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { NextIntlClientProvider } from "next-intl";
import { LocaleProvider } from "@/contexts/LocaleContext";
import { Recursive, Tajawal } from "next/font/google";
import { AppNavbar } from "@/components/Header";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children
}: Readonly<{
  children: React.ReactNode;

}>) {

  return (


    <div className="min-h-screen flex flex-col">
      <AppNavbar />

      <main className="flex-grow">

        {children}
      </main>
      <Footer />
    </div>



  );
}
