import type { Metadata } from "next";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { NextIntlClientProvider } from "next-intl";
import { LocaleProvider } from "@/contexts/LocaleContext";
import { Outfit, Recursive, Tajawal } from "next/font/google";
import { AppNavbar } from "@/components/Header";
import Footer from "@/components/Footer";
import { SidebarProvider } from "@/contexts/SidebarContext";

const outfit = Outfit({
  subsets: ["latin"],
});const tajawal = Tajawal({
  subsets: ['arabic'],
  weight: "700"
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, params
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };

}>) {
  const { locale } = params;

  const isRTL = locale === 'ar';
  return (
    <html dir={isRTL ? 'rtl' : 'ltr'} lang={locale} suppressHydrationWarning>
      <body className={isRTL ? tajawal.className : outfit.className}>

        <NextIntlClientProvider>

          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <LocaleProvider locale={locale}>

            <SidebarProvider>

            {children}

            </SidebarProvider>

        


            </LocaleProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
