import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { NextIntlClientProvider } from "next-intl";
import { LocaleProvider } from "@/contexts/LocaleContext";
import { Recursive, Tajawal } from "next/font/google";
import { AppNavbar } from "@/components/Header";
import Footer from "@/components/Footer";

const recursive = Recursive({ subsets: ["vietnamese"] });
const tajawal = Tajawal({
  subsets: ['arabic'],
  weight: "700"
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, params
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };

}>) {
  const { locale } = params;

  const isRTL = locale === 'ar';
  return (
    <html dir={isRTL ? 'rtl' : 'ltr'} lang={locale} suppressHydrationWarning>
      <body className={isRTL ? tajawal.className : recursive.className}>

        <NextIntlClientProvider>

          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <LocaleProvider locale={locale}>


              <div className="min-h-screen flex flex-col">
                <AppNavbar />

                <main className="flex-grow">
                  
                  {children}
                </main>
                <Footer />
              </div>


            </LocaleProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
